#!/bin/bash
# ADMBROWSER
# This is a sample launcher script
# It assumes you've installed admbrowser to /usr/local/share
# Edit it to fit your system

cd /usr/local/share/admbrowser
python3 admbrowser.py $@
